on:
  push:
    branches:
      - main

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn
          scope: '@tanmen'
          registry-url: https://npm.pkg.github.com
      - run: yarn run pack
      - run: yarn workspaces run semantic-release -e semantic-release-monorepo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
